version:  "3.8"
services:
  goapp:
    image: 620375131649.dkr.ecr.us-east-1.amazonaws.com/my-app:1.2
    ports:
      - 80:80
    restart: always
  mongodb:
    image:  mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      -  MONGO_INITDB_ROOT_USERNAME=admin
      -  MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
  
  mongo-express:
    image:  mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: always
volumes:
  mongo-data: 
    driver: local
